### PR TITLE
Move episode files back to project root

### PR DESCRIPTION
**Pull request by jpsim**
Turns out c0d0f7897124d2f1cbf14cf55047d3f40150000e didn't fully work, the only reason it looked like it did is that files from a previous deployment weren't cleaned up.

image

### CODE REVIEW

**Comment by jpsim** [comment]
FYI @jessesquires

**Comment by jpsim** [comment]
My prognosis was incorrect. Moved back to the `episodes/` and actually fixed in 3ff7ae318154b768f3b76a37acc022ab3150d7ad.

**Comment by jessesquires** [comment]
lol oops 🤣 

thanks @jpsim !

why not just do `git add .` ? (for 3ff7ae318154b768f3b76a37acc022ab3150d7ad)

**Comment by jpsim** [comment]
In case any temporary files get added there we wouldn't want checked in. I can't think of what they'd be but I didn't see a reason to be more broad than `git add episodes`

**Comment by jessesquires** [comment]
👍🏼

**Pull request merged**
